---
- hosts: all
  tasks:
  - name: debug
    debug:
      var: ansible_facts

  - debug:
      msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"

  - name: Template a file
    template:
      src: report.j2
      dest: report.txt
    delegate_to: localhost
    run_once: true
